# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\NAMASIVAAYAM\Documents\Mini Project 3rd Sem\Namas TicTacToe No SQL\python Files\starterPage copy.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_mainWin(object):
    def setupUi(self, mainWin):
        mainWin.setObjectName("mainWin")
        mainWin.resize(1268, 842)
        font = QtGui.QFont()
        font.setFamily("YouYuan")
        mainWin.setFont(font)
        self.centralwidget = QtWidgets.QWidget(mainWin)
        self.centralwidget.setObjectName("centralwidget")
        self.tictactoeTitleLabel = QtWidgets.QLabel(self.centralwidget)
        self.tictactoeTitleLabel.setGeometry(QtCore.QRect(510, 180, 231, 51))
        font = QtGui.QFont()
        font.setFamily("YouYuan")
        font.setPointSize(23)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.tictactoeTitleLabel.setFont(font)
        self.tictactoeTitleLabel.setStyleSheet("background:rgb(0, 255, 238);\n"
"font-color:")
        self.tictactoeTitleLabel.setObjectName("tictactoeTitleLabel")
        self.modeAivsAiButton = QtWidgets.QPushButton(self.centralwidget)
        self.modeAivsAiButton.setGeometry(QtCore.QRect(130, 600, 1000, 28))
        self.modeAivsAiButton.setObjectName("modeAivsAiButton")
        self.mode1vsAiButton = QtWidgets.QPushButton(self.centralwidget)
        self.mode1vsAiButton.setGeometry(QtCore.QRect(130, 640, 1000, 28))
        self.mode1vsAiButton.setObjectName("mode1vsAiButton")
        self.mode1v1Button = QtWidgets.QPushButton(self.centralwidget)
        self.mode1v1Button.setGeometry(QtCore.QRect(130, 680, 1000, 28))
        self.mode1v1Button.setObjectName("mode1v1Button")
        self.poweredByLabel = QtWidgets.QLabel(self.centralwidget)
        self.poweredByLabel.setGeometry(QtCore.QRect(280, 230, 721, 29))
        font = QtGui.QFont()
        font.setFamily("YouYuan")
        font.setPointSize(15)
        font.setBold(False)
        font.setItalic(True)
        font.setUnderline(False)
        font.setWeight(50)
        self.poweredByLabel.setFont(font)
        self.poweredByLabel.setStyleSheet("background-color: rgb(0, 255, 255);")
        self.poweredByLabel.setWordWrap(True)
        self.poweredByLabel.setObjectName("poweredByLabel")
        self.chooseModeLabel = QtWidgets.QLabel(self.centralwidget)
        self.chooseModeLabel.setGeometry(QtCore.QRect(120, 530, 1071, 61))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(15)
        self.chooseModeLabel.setFont(font)
        self.chooseModeLabel.setObjectName("chooseModeLabel")
        mainWin.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(mainWin)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1268, 21))
        self.menubar.setObjectName("menubar")
        mainWin.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(mainWin)
        self.statusbar.setObjectName("statusbar")
        mainWin.setStatusBar(self.statusbar)

        self.retranslateUi(mainWin)
        QtCore.QMetaObject.connectSlotsByName(mainWin)

    def retranslateUi(self, mainWin):
        _translate = QtCore.QCoreApplication.translate
        mainWin.setWindowTitle(_translate("mainWin", "MainWindow"))
        self.tictactoeTitleLabel.setText(_translate("mainWin", "TIC TAC TOE"))
        self.modeAivsAiButton.setText(_translate("mainWin", "NPC vs NPC"))
        self.mode1vsAiButton.setText(_translate("mainWin", "1 vs NPC"))
        self.mode1v1Button.setText(_translate("mainWin", "1 vs 1"))
        self.poweredByLabel.setText(_translate("mainWin", " Powered By Artificial Intelligence (MiniMax Algorithm)"))
        self.chooseModeLabel.setText(_translate("mainWin", "Choose the Game mode you want to play:"))
